### ISSUE TITLE
Make Weather utilize current location

### ISSUE THREAD

**Issue by thedustinsmith** [GolfWithFriends/golf-with-friends#2]
Currently the weather defaults to columbia, MO.  The code looks like it's close to using the location, just need to hook it up.

**Comment by Conroman16** [comment]
Just pinned down why this isn't working on divshot.  We just need to add the golf-with-friends.divshot.io domain to our Google Maps API settings.  

Here's the error on the console on [development.golf-with-friends.divshot.io](http://development.golf-with-friends.divshot.io/location):

```
"This IP, site or mobile application is not authorized to use this API key."
```
